//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateRemoteRequestTransport.
const (
	CreateRemoteRequestTransportHttps CreateRemoteRequestTransport = "https"
	CreateRemoteRequestTransportSsh   CreateRemoteRequestTransport = "ssh"
)

// Valid indicates whether the value is a known member of the CreateRemoteRequestTransport enum.
func (e CreateRemoteRequestTransport) Valid() bool {
	switch e {
	case CreateRemoteRequestTransportHttps:
		return true
	case CreateRemoteRequestTransportSsh:
		return true
	default:
		return false
	}
}

// Defines values for RemoteHashAlgo.
const (
	Sha1   RemoteHashAlgo = "sha1"
	Sha256 RemoteHashAlgo = "sha256"
)

// Valid indicates whether the value is a known member of the RemoteHashAlgo enum.
func (e RemoteHashAlgo) Valid() bool {
	switch e {
	case Sha1:
		return true
	case Sha256:
		return true
	default:
		return false
	}
}

// Defines values for RemoteStatus.
const (
	RemoteStatusActive   RemoteStatus = "active"
	RemoteStatusDegraded RemoteStatus = "degraded"
	RemoteStatusPaused   RemoteStatus = "paused"
)

// Valid indicates whether the value is a known member of the RemoteStatus enum.
func (e RemoteStatus) Valid() bool {
	switch e {
	case RemoteStatusActive:
		return true
	case RemoteStatusDegraded:
		return true
	case RemoteStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for RemoteTransport.
const (
	RemoteTransportHttps RemoteTransport = "https"
	RemoteTransportSsh   RemoteTransport = "ssh"
)

// Valid indicates whether the value is a known member of the RemoteTransport enum.
func (e RemoteTransport) Valid() bool {
	switch e {
	case RemoteTransportHttps:
		return true
	case RemoteTransportSsh:
		return true
	default:
		return false
	}
}

// Defines values for SyncEntryStatus.
const (
	SyncEntryStatusFailed  SyncEntryStatus = "failed"
	SyncEntryStatusOk      SyncEntryStatus = "ok"
	SyncEntryStatusPartial SyncEntryStatus = "partial"
)

// Valid indicates whether the value is a known member of the SyncEntryStatus enum.
func (e SyncEntryStatus) Valid() bool {
	switch e {
	case SyncEntryStatusFailed:
		return true
	case SyncEntryStatusOk:
		return true
	case SyncEntryStatusPartial:
		return true
	default:
		return false
	}
}

// Defines values for SyncEntryTrigger.
const (
	Manual    SyncEntryTrigger = "manual"
	Register  SyncEntryTrigger = "register"
	Scheduled SyncEntryTrigger = "scheduled"
)

// Valid indicates whether the value is a known member of the SyncEntryTrigger enum.
func (e SyncEntryTrigger) Valid() bool {
	switch e {
	case Manual:
		return true
	case Register:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for TaintEventReason.
const (
	TagDeletedRecreated TaintEventReason = "tag_deleted_recreated"
	TagOidChanged       TaintEventReason = "tag_oid_changed"
)

// Valid indicates whether the value is a known member of the TaintEventReason enum.
func (e TaintEventReason) Valid() bool {
	switch e {
	case TagDeletedRecreated:
		return true
	case TagOidChanged:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRemoteRequestStatus.
const (
	UpdateRemoteRequestStatusActive   UpdateRemoteRequestStatus = "active"
	UpdateRemoteRequestStatusDegraded UpdateRemoteRequestStatus = "degraded"
	UpdateRemoteRequestStatusPaused   UpdateRemoteRequestStatus = "paused"
)

// Valid indicates whether the value is a known member of the UpdateRemoteRequestStatus enum.
func (e UpdateRemoteRequestStatus) Valid() bool {
	switch e {
	case UpdateRemoteRequestStatusActive:
		return true
	case UpdateRemoteRequestStatusDegraded:
		return true
	case UpdateRemoteRequestStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResponseConfidence.
const (
	Authoritative VerifyResponseConfidence = "authoritative"
	Stale         VerifyResponseConfidence = "stale"
)

// Valid indicates whether the value is a known member of the VerifyResponseConfidence enum.
func (e VerifyResponseConfidence) Valid() bool {
	switch e {
	case Authoritative:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResponseStatus.
const (
	VerifyResponseStatusDoesntExist VerifyResponseStatus = "doesnt_exist"
	VerifyResponseStatusMismatch    VerifyResponseStatus = "mismatch"
	VerifyResponseStatusNotTracked  VerifyResponseStatus = "not_tracked"
	VerifyResponseStatusOk          VerifyResponseStatus = "ok"
	VerifyResponseStatusTainted     VerifyResponseStatus = "tainted"
)

// Valid indicates whether the value is a known member of the VerifyResponseStatus enum.
func (e VerifyResponseStatus) Valid() bool {
	switch e {
	case VerifyResponseStatusDoesntExist:
		return true
	case VerifyResponseStatusMismatch:
		return true
	case VerifyResponseStatusNotTracked:
		return true
	case VerifyResponseStatusOk:
		return true
	case VerifyResponseStatusTainted:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResponseSyncOutcome.
const (
	VerifyResponseSyncOutcomeFailed VerifyResponseSyncOutcome = "failed"
	VerifyResponseSyncOutcomeNever  VerifyResponseSyncOutcome = "never"
	VerifyResponseSyncOutcomeOk     VerifyResponseSyncOutcome = "ok"
)

// Valid indicates whether the value is a known member of the VerifyResponseSyncOutcome enum.
func (e VerifyResponseSyncOutcome) Valid() bool {
	switch e {
	case VerifyResponseSyncOutcomeFailed:
		return true
	case VerifyResponseSyncOutcomeNever:
		return true
	case VerifyResponseSyncOutcomeOk:
		return true
	default:
		return false
	}
}

// Defines values for ListTagsParamsTainted.
const (
	ListTagsParamsTaintedAny   ListTagsParamsTainted = "any"
	ListTagsParamsTaintedNever ListTagsParamsTainted = "never"
	ListTagsParamsTaintedOnly  ListTagsParamsTainted = "only"
)

// Valid indicates whether the value is a known member of the ListTagsParamsTainted enum.
func (e ListTagsParamsTainted) Valid() bool {
	switch e {
	case ListTagsParamsTaintedAny:
		return true
	case ListTagsParamsTaintedNever:
		return true
	case ListTagsParamsTaintedOnly:
		return true
	default:
		return false
	}
}

// AckRequest defines model for AckRequest.
type AckRequest struct {
	AckNote *string `json:"ack_note,omitempty"`
	AckedBy string  `json:"acked_by"`
}

// CreateRemoteRequest defines model for CreateRemoteRequest.
type CreateRemoteRequest struct {
	StalenessBudgetNs   *int64                       `json:"staleness_budget_ns,omitempty"`
	SyncIntervalNs      *int64                       `json:"sync_interval_ns,omitempty"`
	TaintAnyTagDeletion *bool                        `json:"taint_any_tag_deletion,omitempty"`
	Transport           CreateRemoteRequestTransport `json:"transport"`
	Url                 string                       `json:"url"`
}

// CreateRemoteRequestTransport defines model for CreateRemoteRequest.Transport.
type CreateRemoteRequestTransport string

// Error defines model for Error.
type Error struct {
	Detail *string `json:"detail,omitempty"`
	Error  string  `json:"error"`
}

// Remote defines model for Remote.
type Remote struct {
	ChainLen            int64 `json:"chain_len"`
	ConsecutiveFailures int   `json:"consecutive_failures"`

	// CreatedAtNs unix-nanoseconds
	CreatedAtNs   int64           `json:"created_at_ns"`
	HashAlgo      *RemoteHashAlgo `json:"hash_algo,omitempty"`
	Id            int64           `json:"id"`
	LastErr       string          `json:"last_err"`
	LastOkNs      int64           `json:"last_ok_ns"`
	NormalizedUrl string          `json:"normalized_url"`
	RemovedAtNs   *int64          `json:"removed_at_ns,omitempty"`

	// StalenessBudgetNs unix-nanoseconds
	StalenessBudgetNs int64        `json:"staleness_budget_ns"`
	Status            RemoteStatus `json:"status"`

	// SyncIntervalNs unix-nanoseconds
	SyncIntervalNs      int64           `json:"sync_interval_ns"`
	TaintAnyTagDeletion bool            `json:"taint_any_tag_deletion"`
	Transport           RemoteTransport `json:"transport"`

	// UpdatedAtNs unix-nanoseconds
	UpdatedAtNs int64  `json:"updated_at_ns"`
	Url         string `json:"url"`
}

// RemoteHashAlgo defines model for Remote.HashAlgo.
type RemoteHashAlgo string

// RemoteStatus defines model for Remote.Status.
type RemoteStatus string

// RemoteTransport defines model for Remote.Transport.
type RemoteTransport string

// RemoteList defines model for RemoteList.
type RemoteList struct {
	Items      []Remote `json:"items"`
	NextCursor *int64   `json:"next_cursor,omitempty"`
}

// SyncAuditList defines model for SyncAuditList.
type SyncAuditList struct {
	Items      []SyncEntry `json:"items"`
	NextCursor *int64      `json:"next_cursor,omitempty"`
}

// SyncEntry defines model for SyncEntry.
type SyncEntry struct {
	ChainHeadAfter  *string          `json:"chain_head_after,omitempty"`
	ChainHeadBefore *string          `json:"chain_head_before,omitempty"`
	Error           *string          `json:"error,omitempty"`
	FinishedNs      int64            `json:"finished_ns"`
	Id              int64            `json:"id"`
	RemoteId        int64            `json:"remote_id"`
	StartedNs       int64            `json:"started_ns"`
	Status          SyncEntryStatus  `json:"status"`
	TagsChanged     int              `json:"tags_changed"`
	TagsSeen        int              `json:"tags_seen"`
	Trigger         SyncEntryTrigger `json:"trigger"`
}

// SyncEntryStatus defines model for SyncEntry.Status.
type SyncEntryStatus string

// SyncEntryTrigger defines model for SyncEntry.Trigger.
type SyncEntryTrigger string

// Tag defines model for Tag.
type Tag struct {
	CurrentOid       *string `json:"current_oid,omitempty"`
	CurrentPeeledOid *string `json:"current_peeled_oid,omitempty"`
	Deleted          bool    `json:"deleted"`
	FirstOid         *string `json:"first_oid,omitempty"`
	FirstSeenNs      int64   `json:"first_seen_ns"`
	Id               int64   `json:"id"`
	IsAnnotated      *bool   `json:"is_annotated,omitempty"`
	LastChangedNs    *int64  `json:"last_changed_ns,omitempty"`
	LastSeenNs       int64   `json:"last_seen_ns"`
	ObservationCount int64   `json:"observation_count"`
	RemoteId         int64   `json:"remote_id"`
	TagName          string  `json:"tag_name"`
	TaintFirstNs     *int64  `json:"taint_first_ns,omitempty"`
	Tainted          bool    `json:"tainted"`
}

// TagList defines model for TagList.
type TagList struct {
	Items      []Tag  `json:"items"`
	NextCursor *int64 `json:"next_cursor,omitempty"`
}

// TaintEvent defines model for TaintEvent.
type TaintEvent struct {
	AckNote       *string          `json:"ack_note,omitempty"`
	AckedAtNs     *int64           `json:"acked_at_ns,omitempty"`
	AckedBy       *string          `json:"acked_by,omitempty"`
	Detail        *string          `json:"detail,omitempty"`
	DetectedAtNs  int64            `json:"detected_at_ns"`
	FromOid       *string          `json:"from_oid,omitempty"`
	Id            int64            `json:"id"`
	ObservationId *int64           `json:"observation_id,omitempty"`
	Reason        TaintEventReason `json:"reason"`
	RefId         int64            `json:"ref_id"`
	RemoteId      int64            `json:"remote_id"`
	ToOid         *string          `json:"to_oid,omitempty"`
}

// TaintEventReason defines model for TaintEvent.Reason.
type TaintEventReason string

// TaintEventList defines model for TaintEventList.
type TaintEventList struct {
	Items      []TaintEvent `json:"items"`
	NextCursor *int64       `json:"next_cursor,omitempty"`
}

// UpdateRemoteRequest defines model for UpdateRemoteRequest.
type UpdateRemoteRequest struct {
	StalenessBudgetNs   *int64                     `json:"staleness_budget_ns,omitempty"`
	Status              *UpdateRemoteRequestStatus `json:"status,omitempty"`
	SyncIntervalNs      *int64                     `json:"sync_interval_ns,omitempty"`
	TaintAnyTagDeletion *bool                      `json:"taint_any_tag_deletion,omitempty"`
}

// UpdateRemoteRequestStatus defines model for UpdateRemoteRequest.Status.
type UpdateRemoteRequestStatus string

// VerifyResponse defines model for VerifyResponse.
type VerifyResponse struct {
	Confidence   VerifyResponseConfidence `json:"confidence"`
	LastSyncedNs *int64                   `json:"last_synced_ns,omitempty"`
	LedgerProof  *struct {
		RemoteId *int64  `json:"remote_id,omitempty"`
		RowHash  *string `json:"row_hash,omitempty"`
		Seq      *int64  `json:"seq,omitempty"`
	} `json:"ledger_proof,omitempty"`
	Recorded *struct {
		FirstSeenNs     *int64  `json:"first_seen_ns,omitempty"`
		LastSeenNs      *int64  `json:"last_seen_ns,omitempty"`
		PeeledCommitOid *string `json:"peeled_commit_oid,omitempty"`
		RefOid          *string `json:"ref_oid,omitempty"`
	} `json:"recorded,omitempty"`
	Remote *struct {
		Id            *int64  `json:"id,omitempty"`
		NormalizedUrl *string `json:"normalized_url,omitempty"`
	} `json:"remote,omitempty"`
	Status         VerifyResponseStatus       `json:"status"`
	SuppliedCommit *string                    `json:"supplied_commit,omitempty"`
	SyncOutcome    *VerifyResponseSyncOutcome `json:"sync_outcome,omitempty"`
	Tag            string                     `json:"tag"`
	Taint          *struct {
		FirstTaintedAtNs *int64  `json:"first_tainted_at_ns,omitempty"`
		FromOid          *string `json:"from_oid,omitempty"`
		Reason           *string `json:"reason,omitempty"`
		ToOid            *string `json:"to_oid,omitempty"`
	} `json:"taint,omitempty"`
}

// VerifyResponseConfidence defines model for VerifyResponse.Confidence.
type VerifyResponseConfidence string

// VerifyResponseStatus defines model for VerifyResponse.Status.
type VerifyResponseStatus string

// VerifyResponseSyncOutcome defines model for VerifyResponse.SyncOutcome.
type VerifyResponseSyncOutcome string

// ListRemotesParams defines parameters for ListRemotes.
type ListRemotesParams struct {
	// Url Resolve a normalized URL to its remote (exact match).
	Url    *string `form:"url,omitempty" json:"url,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *int64  `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSyncsParams defines parameters for ListSyncs.
type ListSyncsParams struct {
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *int64 `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	// Q Glob pattern for tag name filter (default = all).
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Tainted Filter by taint status.
	Tainted *ListTagsParamsTainted `form:"tainted,omitempty" json:"tainted,omitempty"`
	Limit   *int                   `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *int64                 `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTagsParamsTainted defines parameters for ListTags.
type ListTagsParamsTainted string

// ListTaintEventsParams defines parameters for ListTaintEvents.
type ListTaintEventsParams struct {
	Limit  *int   `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *int64 `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// VerifyParams defines parameters for Verify.
type VerifyParams struct {
	// Remote Normalized URL or remote id.
	Remote string `form:"remote" json:"remote"`
	Tag    string `form:"tag" json:"tag"`

	// Commit Expected peeled commit oid (hex, 40 or 64 chars). Optional.
	Commit *string `form:"commit,omitempty" json:"commit,omitempty"`
}

// CreateRemoteJSONRequestBody defines body for CreateRemote for application/json ContentType.
type CreateRemoteJSONRequestBody = CreateRemoteRequest

// UpdateRemoteJSONRequestBody defines body for UpdateRemote for application/json ContentType.
type UpdateRemoteJSONRequestBody = UpdateRemoteRequest

// AckTaintEventJSONRequestBody defines body for AckTaintEvent for application/json ContentType.
type AckTaintEventJSONRequestBody = AckRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// List all remotes (paginated).
	// (GET /v1/remotes)
	ListRemotes(w http.ResponseWriter, r *http.Request, params ListRemotesParams)
	// Register a new remote.
	// (POST /v1/remotes)
	CreateRemote(w http.ResponseWriter, r *http.Request)
	// Soft-delete a remote (retain ledger + taint history).
	// (DELETE /v1/remotes/{remoteId})
	DeleteRemote(w http.ResponseWriter, r *http.Request, remoteId int64)
	// Get one remote by id.
	// (GET /v1/remotes/{remoteId})
	GetRemote(w http.ResponseWriter, r *http.Request, remoteId int64)
	// Update remote settings.
	// (PATCH /v1/remotes/{remoteId})
	UpdateRemote(w http.ResponseWriter, r *http.Request, remoteId int64)
	// Trigger an on-demand sync for a remote (202 Accepted).
	// (POST /v1/remotes/{remoteId}/sync)
	TriggerSync(w http.ResponseWriter, r *http.Request, remoteId int64)
	// List sync audit rows for a remote (paginated).
	// (GET /v1/remotes/{remoteId}/syncs)
	ListSyncs(w http.ResponseWriter, r *http.Request, remoteId int64, params ListSyncsParams)
	// List tag projections for a remote.
	// (GET /v1/remotes/{remoteId}/tags)
	ListTags(w http.ResponseWriter, r *http.Request, remoteId int64, params ListTagsParams)
	// Get a single tag projection by name.
	// (GET /v1/remotes/{remoteId}/tags/{tagName})
	GetTag(w http.ResponseWriter, r *http.Request, remoteId int64, tagName string)
	// List taint events for a remote (paginated).
	// (GET /v1/remotes/{remoteId}/taint-events)
	ListTaintEvents(w http.ResponseWriter, r *http.Request, remoteId int64, params ListTaintEventsParams)
	// Annotate a taint event as acknowledged (append-only; does not clear taint).
	// (POST /v1/remotes/{remoteId}/taint-events/{eventId}/ack)
	AckTaintEvent(w http.ResponseWriter, r *http.Request, remoteId int64, eventId int64)
	// Verify a tag on a remote against the ledger.
	// (GET /v1/verify)
	Verify(w http.ResponseWriter, r *http.Request, params VerifyParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRemotes operation middleware
func (siw *ServerInterfaceWrapper) ListRemotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRemotesParams

	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "url", r.URL.Query(), &params.Url, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "url"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "url", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRemotes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRemote operation middleware
func (siw *ServerInterfaceWrapper) CreateRemote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRemote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRemote operation middleware
func (siw *ServerInterfaceWrapper) DeleteRemote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRemote(w, r, remoteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRemote operation middleware
func (siw *ServerInterfaceWrapper) GetRemote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRemote(w, r, remoteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRemote operation middleware
func (siw *ServerInterfaceWrapper) UpdateRemote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRemote(w, r, remoteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r, remoteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSyncs operation middleware
func (siw *ServerInterfaceWrapper) ListSyncs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSyncsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSyncs(w, r, remoteId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTagsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tainted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tainted", r.URL.Query(), &params.Tainted, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tainted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tainted", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTags(w, r, remoteId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTag operation middleware
func (siw *ServerInterfaceWrapper) GetTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	// ------------- Path parameter "tagName" -------------
	var tagName string

	err = runtime.BindStyledParameterWithOptions("simple", "tagName", r.PathValue("tagName"), &tagName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTag(w, r, remoteId, tagName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTaintEvents operation middleware
func (siw *ServerInterfaceWrapper) ListTaintEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTaintEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTaintEvents(w, r, remoteId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AckTaintEvent operation middleware
func (siw *ServerInterfaceWrapper) AckTaintEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "remoteId" -------------
	var remoteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "remoteId", r.PathValue("remoteId"), &remoteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remoteId", Err: err})
		return
	}

	// ------------- Path parameter "eventId" -------------
	var eventId int64

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AckTaintEvent(w, r, remoteId, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Verify operation middleware
func (siw *ServerInterfaceWrapper) Verify(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyParams

	// ------------- Required query parameter "remote" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "remote", r.URL.Query(), &params.Remote, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "remote"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "remote", Err: err})
		}
		return
	}

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "commit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "commit", r.URL.Query(), &params.Commit, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "commit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Verify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes", wrapper.ListRemotes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/remotes", wrapper.CreateRemote)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/remotes/{remoteId}", wrapper.DeleteRemote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes/{remoteId}", wrapper.GetRemote)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/remotes/{remoteId}", wrapper.UpdateRemote)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/remotes/{remoteId}/sync", wrapper.TriggerSync)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes/{remoteId}/syncs", wrapper.ListSyncs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes/{remoteId}/tags", wrapper.ListTags)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes/{remoteId}/tags/{tagName}", wrapper.GetTag)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/remotes/{remoteId}/taint-events", wrapper.ListTaintEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/remotes/{remoteId}/taint-events/{eventId}/ack", wrapper.AckTaintEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/verify", wrapper.Verify)

	return m
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200TextResponse string

func (response GetHealthz200TextResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type ListRemotesRequestObject struct {
	Params ListRemotesParams
}

type ListRemotesResponseObject interface {
	VisitListRemotesResponse(w http.ResponseWriter) error
}

type ListRemotes200JSONResponse RemoteList

func (response ListRemotes200JSONResponse) VisitListRemotesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRemoteRequestObject struct {
	Body *CreateRemoteJSONRequestBody
}

type CreateRemoteResponseObject interface {
	VisitCreateRemoteResponse(w http.ResponseWriter) error
}

type CreateRemote201JSONResponse Remote

func (response CreateRemote201JSONResponse) VisitCreateRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRemote409JSONResponse Error

func (response CreateRemote409JSONResponse) VisitCreateRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRemote422JSONResponse Error

func (response CreateRemote422JSONResponse) VisitCreateRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRemoteRequestObject struct {
	RemoteId int64 `json:"remoteId"`
}

type DeleteRemoteResponseObject interface {
	VisitDeleteRemoteResponse(w http.ResponseWriter) error
}

type DeleteRemote204Response struct {
}

func (response DeleteRemote204Response) VisitDeleteRemoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRemote404JSONResponse Error

func (response DeleteRemote404JSONResponse) VisitDeleteRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRemoteRequestObject struct {
	RemoteId int64 `json:"remoteId"`
}

type GetRemoteResponseObject interface {
	VisitGetRemoteResponse(w http.ResponseWriter) error
}

type GetRemote200JSONResponse Remote

func (response GetRemote200JSONResponse) VisitGetRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRemote404JSONResponse Error

func (response GetRemote404JSONResponse) VisitGetRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRemoteRequestObject struct {
	RemoteId int64 `json:"remoteId"`
	Body     *UpdateRemoteJSONRequestBody
}

type UpdateRemoteResponseObject interface {
	VisitUpdateRemoteResponse(w http.ResponseWriter) error
}

type UpdateRemote200JSONResponse Remote

func (response UpdateRemote200JSONResponse) VisitUpdateRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRemote404JSONResponse Error

func (response UpdateRemote404JSONResponse) VisitUpdateRemoteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSyncRequestObject struct {
	RemoteId int64 `json:"remoteId"`
}

type TriggerSyncResponseObject interface {
	VisitTriggerSyncResponse(w http.ResponseWriter) error
}

type TriggerSync202Response struct {
}

func (response TriggerSync202Response) VisitTriggerSyncResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerSync404JSONResponse Error

func (response TriggerSync404JSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSync429JSONResponse Error

func (response TriggerSync429JSONResponse) VisitTriggerSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListSyncsRequestObject struct {
	RemoteId int64 `json:"remoteId"`
	Params   ListSyncsParams
}

type ListSyncsResponseObject interface {
	VisitListSyncsResponse(w http.ResponseWriter) error
}

type ListSyncs200JSONResponse SyncAuditList

func (response ListSyncs200JSONResponse) VisitListSyncsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSyncs404JSONResponse Error

func (response ListSyncs404JSONResponse) VisitListSyncsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTagsRequestObject struct {
	RemoteId int64 `json:"remoteId"`
	Params   ListTagsParams
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse TagList

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTags404JSONResponse Error

func (response ListTags404JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTags422JSONResponse Error

func (response ListTags422JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagRequestObject struct {
	RemoteId int64  `json:"remoteId"`
	TagName  string `json:"tagName"`
}

type GetTagResponseObject interface {
	VisitGetTagResponse(w http.ResponseWriter) error
}

type GetTag200JSONResponse Tag

func (response GetTag200JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTag404JSONResponse Error

func (response GetTag404JSONResponse) VisitGetTagResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListTaintEventsRequestObject struct {
	RemoteId int64 `json:"remoteId"`
	Params   ListTaintEventsParams
}

type ListTaintEventsResponseObject interface {
	VisitListTaintEventsResponse(w http.ResponseWriter) error
}

type ListTaintEvents200JSONResponse TaintEventList

func (response ListTaintEvents200JSONResponse) VisitListTaintEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTaintEvents404JSONResponse Error

func (response ListTaintEvents404JSONResponse) VisitListTaintEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AckTaintEventRequestObject struct {
	RemoteId int64 `json:"remoteId"`
	EventId  int64 `json:"eventId"`
	Body     *AckTaintEventJSONRequestBody
}

type AckTaintEventResponseObject interface {
	VisitAckTaintEventResponse(w http.ResponseWriter) error
}

type AckTaintEvent204Response struct {
}

func (response AckTaintEvent204Response) VisitAckTaintEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AckTaintEvent404JSONResponse Error

func (response AckTaintEvent404JSONResponse) VisitAckTaintEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AckTaintEvent409JSONResponse Error

func (response AckTaintEvent409JSONResponse) VisitAckTaintEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AckTaintEvent422JSONResponse Error

func (response AckTaintEvent422JSONResponse) VisitAckTaintEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyRequestObject struct {
	Params VerifyParams
}

type VerifyResponseObject interface {
	VisitVerifyResponse(w http.ResponseWriter) error
}

type Verify200JSONResponse VerifyResponse

func (response Verify200JSONResponse) VisitVerifyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Verify422JSONResponse Error

func (response Verify422JSONResponse) VisitVerifyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe.
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// List all remotes (paginated).
	// (GET /v1/remotes)
	ListRemotes(ctx context.Context, request ListRemotesRequestObject) (ListRemotesResponseObject, error)
	// Register a new remote.
	// (POST /v1/remotes)
	CreateRemote(ctx context.Context, request CreateRemoteRequestObject) (CreateRemoteResponseObject, error)
	// Soft-delete a remote (retain ledger + taint history).
	// (DELETE /v1/remotes/{remoteId})
	DeleteRemote(ctx context.Context, request DeleteRemoteRequestObject) (DeleteRemoteResponseObject, error)
	// Get one remote by id.
	// (GET /v1/remotes/{remoteId})
	GetRemote(ctx context.Context, request GetRemoteRequestObject) (GetRemoteResponseObject, error)
	// Update remote settings.
	// (PATCH /v1/remotes/{remoteId})
	UpdateRemote(ctx context.Context, request UpdateRemoteRequestObject) (UpdateRemoteResponseObject, error)
	// Trigger an on-demand sync for a remote (202 Accepted).
	// (POST /v1/remotes/{remoteId}/sync)
	TriggerSync(ctx context.Context, request TriggerSyncRequestObject) (TriggerSyncResponseObject, error)
	// List sync audit rows for a remote (paginated).
	// (GET /v1/remotes/{remoteId}/syncs)
	ListSyncs(ctx context.Context, request ListSyncsRequestObject) (ListSyncsResponseObject, error)
	// List tag projections for a remote.
	// (GET /v1/remotes/{remoteId}/tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
	// Get a single tag projection by name.
	// (GET /v1/remotes/{remoteId}/tags/{tagName})
	GetTag(ctx context.Context, request GetTagRequestObject) (GetTagResponseObject, error)
	// List taint events for a remote (paginated).
	// (GET /v1/remotes/{remoteId}/taint-events)
	ListTaintEvents(ctx context.Context, request ListTaintEventsRequestObject) (ListTaintEventsResponseObject, error)
	// Annotate a taint event as acknowledged (append-only; does not clear taint).
	// (POST /v1/remotes/{remoteId}/taint-events/{eventId}/ack)
	AckTaintEvent(ctx context.Context, request AckTaintEventRequestObject) (AckTaintEventResponseObject, error)
	// Verify a tag on a remote against the ledger.
	// (GET /v1/verify)
	Verify(ctx context.Context, request VerifyRequestObject) (VerifyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRemotes operation middleware
func (sh *strictHandler) ListRemotes(w http.ResponseWriter, r *http.Request, params ListRemotesParams) {
	var request ListRemotesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRemotes(ctx, request.(ListRemotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRemotes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRemotesResponseObject); ok {
		if err := validResponse.VisitListRemotesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRemote operation middleware
func (sh *strictHandler) CreateRemote(w http.ResponseWriter, r *http.Request) {
	var request CreateRemoteRequestObject

	var body CreateRemoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRemote(ctx, request.(CreateRemoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRemote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateRemoteResponseObject); ok {
		if err := validResponse.VisitCreateRemoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRemote operation middleware
func (sh *strictHandler) DeleteRemote(w http.ResponseWriter, r *http.Request, remoteId int64) {
	var request DeleteRemoteRequestObject

	request.RemoteId = remoteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRemote(ctx, request.(DeleteRemoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRemote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteRemoteResponseObject); ok {
		if err := validResponse.VisitDeleteRemoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRemote operation middleware
func (sh *strictHandler) GetRemote(w http.ResponseWriter, r *http.Request, remoteId int64) {
	var request GetRemoteRequestObject

	request.RemoteId = remoteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRemote(ctx, request.(GetRemoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRemote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRemoteResponseObject); ok {
		if err := validResponse.VisitGetRemoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRemote operation middleware
func (sh *strictHandler) UpdateRemote(w http.ResponseWriter, r *http.Request, remoteId int64) {
	var request UpdateRemoteRequestObject

	request.RemoteId = remoteId

	var body UpdateRemoteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRemote(ctx, request.(UpdateRemoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRemote")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateRemoteResponseObject); ok {
		if err := validResponse.VisitUpdateRemoteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSync operation middleware
func (sh *strictHandler) TriggerSync(w http.ResponseWriter, r *http.Request, remoteId int64) {
	var request TriggerSyncRequestObject

	request.RemoteId = remoteId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSync(ctx, request.(TriggerSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSyncResponseObject); ok {
		if err := validResponse.VisitTriggerSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSyncs operation middleware
func (sh *strictHandler) ListSyncs(w http.ResponseWriter, r *http.Request, remoteId int64, params ListSyncsParams) {
	var request ListSyncsRequestObject

	request.RemoteId = remoteId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSyncs(ctx, request.(ListSyncsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSyncs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSyncsResponseObject); ok {
		if err := validResponse.VisitListSyncsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(w http.ResponseWriter, r *http.Request, remoteId int64, params ListTagsParams) {
	var request ListTagsRequestObject

	request.RemoteId = remoteId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTag operation middleware
func (sh *strictHandler) GetTag(w http.ResponseWriter, r *http.Request, remoteId int64, tagName string) {
	var request GetTagRequestObject

	request.RemoteId = remoteId
	request.TagName = tagName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTag(ctx, request.(GetTagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTagResponseObject); ok {
		if err := validResponse.VisitGetTagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTaintEvents operation middleware
func (sh *strictHandler) ListTaintEvents(w http.ResponseWriter, r *http.Request, remoteId int64, params ListTaintEventsParams) {
	var request ListTaintEventsRequestObject

	request.RemoteId = remoteId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTaintEvents(ctx, request.(ListTaintEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTaintEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTaintEventsResponseObject); ok {
		if err := validResponse.VisitListTaintEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AckTaintEvent operation middleware
func (sh *strictHandler) AckTaintEvent(w http.ResponseWriter, r *http.Request, remoteId int64, eventId int64) {
	var request AckTaintEventRequestObject

	request.RemoteId = remoteId
	request.EventId = eventId

	var body AckTaintEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AckTaintEvent(ctx, request.(AckTaintEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AckTaintEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AckTaintEventResponseObject); ok {
		if err := validResponse.VisitAckTaintEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Verify operation middleware
func (sh *strictHandler) Verify(w http.ResponseWriter, r *http.Request, params VerifyParams) {
	var request VerifyRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Verify(ctx, request.(VerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Verify")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyResponseObject); ok {
		if err := validResponse.VisitVerifyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvfc9u48f9XMPjmwZ7TD9pfx5fTTR/cNpdmJnO9cXx9iXOcFbEiEZMAA4CydK7+9w5ASqJIUJJdWU5n",
	"8pJIFIBd7H72s7sA/UAjmeVSoDCajh6ojhLMwH28iu6u8WuB2thvuZI5KsPR/QbRXSikQfs5g9kHFLFJ",
	"6Og8uHjTo2aeIx1RbRQXMV307Ghk4XjeHP36skczLpbfz1pTFz2q8GvBFTI6+rRe5/NqpBx/wchYIX9T",
	"CAavMZP23w69tYEUBWodjgsWowmFezyRKgNDR5QLc3lBnVY8KzI6ClaSuDAYo7Ki9FxEof2uppA+bQkD",
	"XJgQxDw0EIcMUzRcCrsQwwkUqaEjowpcTR1LmSIIN1WB0LlUbnsorIhPNDEm17RHtU5q1lm7oFCp11eP",
	"Mb9doy7e54W3SknVtjtDA9xp0NIMlzO2Cy+H+USWLm/LjBLgIkxReN3TdkkkhcaoMHyK4QR4WqhyHc9I",
	"BzUWwhI/DHWkeF66kBaCz/oChNQYScGsW/YQn4BOQkhjWXerTuDMejWB89eXdveiSFMYp9iAx9qcnO25",
	"3RS0CVEpr1Pcj/KuC9vt1YQdkvI/kYUV1FprKszktG611rIdm6tHnj9+D2F/bcAUum58iCwWaI8yjBUw",
	"ZLRHcyg0Mm+I+VjhEIp1U8WhuCFnh4ezHwWNoObWpCWtNABU34rHtH4kdNpq5d0NZNdioCP6ezUSaYZ9",
	"027d1PSB+1IRN5htfnilcEJH9P+G65Q8rPLxsCK5xUoIKAVzF3k4M2FUKF2y6E7XNF3gpPuU/zgX0VXB",
	"uDmE/naxt8Ko+dG3UErtyA4JAgthYtAJ3kmutUljnEiFe83qynA9OuGC6wTZ/jy7N70rB5hw7/HagDKP",
	"0aTNl/LOEaQyHGwA2yjqoEoDsQ6jBESMzJ9i3QiNKDp+VjyOS6ctpSuMubaO7LkilhWpI+wMRAGpRwsf",
	"Fa2NthaxYZpNl9VoZa1vY3c+WN5A7AFkoRQKE8rSZbuxWI3PEVNke09znLhh9Vr6mHCl99egHG03/Qz4",
	"5ToEIaSBTmUdeVdm3l8BN+txOsuxtonHZpIwkoUwzxSCNmUJyNBLFWVmK03+5PLJLeK3585wWCq3XmUN",
	"piYWGmb2mbAjLg6Ra2x4HTPL3Fh7vJ2i2NEo7wyosr/9b+rjeqe9BxV0NmUMDUZmqzJt4RMls73JY++o",
	"qEOnY9JuuygEXdbMy3Rh8Sw5W/F0ifAK0KHCqtjzpi+Fk/DZErGRe9pwV8RWWq423/LqdiwfJhJXkXHM",
	"gPzdFebHOQp6jq7xYGdJHpJvGetfqPhkfo06tx2Qpy6RYsIZigg3dlmYRCpuoNqss6Z3g2UmmIvoUVka",
	"WYwqzJWUE18obKr42BBT8j5MQCde6tP4dV80tmypMJKKIdut8lNqpyeULlVxGMks4/sXdpY5qrFtzvFs",
	"OutIcA3qYIc6S/Jp0dGOrGuVjOsMTJTYyJSohQlxZinOyjOhUS51+kO0yPOUr8y4lwldWMvCRDLDllJV",
	"Z2QZcIqqq0PqLgP3hVe1+edL4uu02lb0EWms4cwGz696rBoTlQZqc7+dy8VEtk+xbiDuu20qbuak5JcB",
	"+U2mqSYxN6REse6RMklqYiAmCu8Vd09B6HtUmkwdW5KvBSqOekA+SJmPIbojQyIkgTwnlhl/JkYV2mgC",
	"glhJJFdyNh/cuu6QG2sLGnPTrxxErn57T3t0ikqXygaDs0Hgip8cBeScjuj/u0c2lZjE+XKYIKQm+dN+",
	"jtFhwiLAFUrvGR3Rd2j+UQ2xBi353U09D4KK2U1VtBqcmWGeAhfrSyAH2xlkuVO3jKaG61ylWLeyLdV4",
	"hIRrktrEsHDhk2Wg5nREP/Cpy7jWHGMcuF+H07NhZfvOndhS5Loa404YIEODStPRp6abr1HLdIoEyJpF",
	"yO/XH4iRhBtduZmc4AwiQxwhnA6oBQ0dUevVuQ1L14RVB5NrYzz28uTBu2rKLYfU113d+JwFQc9KKXP9",
	"WeC+LlP/mS8F+UVUNZVXRtB7XHmx+LwTPGDpMXLuGn6p+GAtefeppqs0PWCqfJWWP28CSRsCabqMWnKS",
	"Q8yFLdhPBy7vSe3BUf2KkJYkg9r8VbL5wXbku4VcbDKaZcFFy6hnBzaqz6DLnmbRoxfBTwcTWN75eeSx",
	"olwSSSOlWwXOz59fAS6mkHJG1MoTdRRdVyeGlizwvsJSi5WGD+WH92xRBpLtENvY+rt7XsPWhncv2glJ",
	"y4npV/0mOdm4HCMazWnppYvnN5KQhkxkIVjDPB/XChJYEadCm7SqBEp+IC6FkYRrI9W8DL6ubNRlnOAI",
	"0Fer+5MXtek7NEQKXFpzPCeclYS1mdQcq9tUvyb1JQppk0vqNN9N7Wd+as9dSdzyVr2Dfiam9DXpezHl",
	"MeBSXe2RbwQ2pa2WqNFoDBex3kZVQ9uAuGb+pYDlzcA35aXKR6tcy7HnHpKci8gW28Uyax3XCTZNHSFP",
	"TqSKkBG3WQUG+65GtGkhkjJl8l4QqxSmkGtkpw1wVDa1vYYUfYYZiGqtiVQ15j4PzslVFGFeVUnbsbO9",
	"Gv/oRvhp63u9u/UWfH2l7uufrNvKgveFKceV2E4dsAoTJe91A1DNmvtFmKYbxQbi7SC+sQN29JPvUjkm",
	"ORiDSrjtG4iJ3Q6Z8NTWjicV0shfbEPS2Ut+7ewkX196W8dNNX4phY3nVb1Vnol0CVsfenkCgoKwQ1cH",
	"ue6bFOl8y3nU9152d4QtLy89MWYx81JB/U10Wo5MrBVyJb9gZOdsksk3SyDDBwPxr5DhYts52w3E9Hmh",
	"1QGrb6KhAaK5iFNseNiylfXby/m25xVUOXSrnA2Cft086avyAR3RPz79cXs7C4L+7e3sPLi9nf04+fzD",
	"K89J6VaYcWH6OF2+gr8lXy1vU7+XXk+IoY2LbW842czq/PANlWA1rf7n6q81rocP7n/7GKK7F+tL/YRQ",
	"qXaM/vcququ9E/E8Byu1v9vZ6zzFczYJ0Z2Q9+6M76X67mOcT0OqENictLb78hXTVfXuI4E6AxDQG8qS",
	"E8hzFKxv6/efCZOo3UlBlCKocmKt0y/vLjtTTPkiyK6G6NfNazWplnTEWVc7ourHiLvz7dOv1kxVhh0t",
	"q7f6tLez3L1hRcoXL0j5xgCRnJGTBGc9chFYk11ekCgBpU8H5J9uKqRdxqveOejYxuXFpt5B/yfoT676",
	"v3x+uAgWr/698eTyYuEtTZ4x6zZeLvKEQXWhrlDbJvoE0nuYa3IeBC7ZpTLmEaRkiorxyOjTo4VnBqnl",
	"fGSEi7xohme5LxecMZFinZQhBi5s2k5w+ZJBubpGNfVHVLp8heCk9gbBafWHMSP31zuj4fDs/MdBMAgG",
	"Z6M3wZuALj4v/hMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
