// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taint.sql

package sqlc

import (
	"context"
)

const ackTaintEvent = `-- name: AckTaintEvent :exec
UPDATE taint_events
SET acked_at_ns = ?, acked_by = ?, ack_note = ?
WHERE id = ? AND acked_at_ns IS NULL
`

type AckTaintEventParams struct {
	AckedAtNs interface{}
	AckedBy   interface{}
	AckNote   interface{}
	ID        int64
}

func (q *Queries) AckTaintEvent(ctx context.Context, arg AckTaintEventParams) error {
	_, err := q.db.ExecContext(ctx, ackTaintEvent,
		arg.AckedAtNs,
		arg.AckedBy,
		arg.AckNote,
		arg.ID,
	)
	return err
}

const insertTaintEvent = `-- name: InsertTaintEvent :one
INSERT INTO taint_events (
  remote_id, ref_id, reason,
  observation_id, from_oid, to_oid,
  detected_at_ns, detail
) VALUES (?,?,?,?,?,?,?,?)
ON CONFLICT (remote_id, ref_id, reason, from_oid, to_oid)
DO UPDATE SET detected_at_ns = detected_at_ns  -- idempotent; keep original
RETURNING id
`

type InsertTaintEventParams struct {
	RemoteID      int64
	RefID         int64
	Reason        string
	ObservationID interface{}
	FromOid       interface{}
	ToOid         interface{}
	DetectedAtNs  int64
	Detail        string
}

func (q *Queries) InsertTaintEvent(ctx context.Context, arg InsertTaintEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTaintEvent,
		arg.RemoteID,
		arg.RefID,
		arg.Reason,
		arg.ObservationID,
		arg.FromOid,
		arg.ToOid,
		arg.DetectedAtNs,
		arg.Detail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTaintEvents = `-- name: ListTaintEvents :many
SELECT id, remote_id, ref_id, reason,
       observation_id, from_oid, to_oid,
       detected_at_ns, acked_at_ns, acked_by, ack_note, detail
FROM taint_events
WHERE remote_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListTaintEventsParams struct {
	RemoteID int64
	ID       int64
	Limit    int64
}

func (q *Queries) ListTaintEvents(ctx context.Context, arg ListTaintEventsParams) ([]TaintEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTaintEvents, arg.RemoteID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaintEvent{}
	for rows.Next() {
		var i TaintEvent
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.RefID,
			&i.Reason,
			&i.ObservationID,
			&i.FromOid,
			&i.ToOid,
			&i.DetectedAtNs,
			&i.AckedAtNs,
			&i.AckedBy,
			&i.AckNote,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
