// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lease.sql

package mysqlc

import (
	"context"
)

const deleteRemoteLease = `-- name: DeleteRemoteLease :exec

DELETE FROM remote_lease WHERE remote_id = ? AND holder = ?
`

type DeleteRemoteLeaseParams struct {
	RemoteID int64
	Holder   string
}

// UpsertRemoteLease is NOT generated by sqlc; implemented manually in mysql.go
// to allow a 5th positional parameter (now_ns) in the freshness predicate.
// This placeholder comment prevents sqlc from erroring on a missing INSERT query.
func (q *Queries) DeleteRemoteLease(ctx context.Context, arg DeleteRemoteLeaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteRemoteLease, arg.RemoteID, arg.Holder)
	return err
}

const getRemoteLease = `-- name: GetRemoteLease :one
SELECT remote_id, holder, acquired_at_ns, expires_at_ns FROM remote_lease WHERE remote_id = ?
`

func (q *Queries) GetRemoteLease(ctx context.Context, remoteID int64) (RemoteLease, error) {
	row := q.db.QueryRowContext(ctx, getRemoteLease, remoteID)
	var i RemoteLease
	err := row.Scan(
		&i.RemoteID,
		&i.Holder,
		&i.AcquiredAtNs,
		&i.ExpiresAtNs,
	)
	return i, err
}
