// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqlc

import (
	"database/sql"
)

type Observation struct {
	ID            int64
	RemoteID      int64
	RefID         int64
	SyncID        int64
	Seq           int64
	EventType     string
	PrevOid       sql.NullString
	NewOid        sql.NullString
	PrevPeeledOid sql.NullString
	NewPeeledOid  sql.NullString
	ObservedAtNs  int64
	PrevHash      []byte
	RowHash       []byte
	CanonicalMeta sql.NullString
}

type Ref struct {
	ID               int64
	RemoteID         int64
	TagName          string
	CurrentOid       sql.NullString
	CurrentPeeledOid sql.NullString
	IsAnnotated      int32
	FirstOid         sql.NullString
	FirstSeenNs      int64
	LastSeenNs       int64
	LastChangedNs    int64
	Deleted          int32
	Tainted          int32
	TaintFirstNs     sql.NullInt64
	ObservationCount int64
}

type Remote struct {
	ID                  int64
	Url                 string
	NormalizedUrl       string
	Transport           string
	SyncIntervalNs      int64
	StalenessBudgetNs   int64
	TaintAnyTagDeletion int32
	HashAlgo            sql.NullString
	Status              string
	LastOkNs            int64
	LastErr             string
	ConsecutiveFailures int32
	ChainHeadHash       []byte
	ChainLen            int64
	RemovedAtNs         sql.NullInt64
	CreatedAtNs         int64
	UpdatedAtNs         int64
}

type RemoteLease struct {
	RemoteID     int64
	Holder       string
	AcquiredAtNs int64
	ExpiresAtNs  int64
}

type SchemaMigration struct {
	Version     int32
	AppliedAtNs int64
}

type Sync struct {
	ID              int64
	RemoteID        int64
	Trigger         string
	StartedNs       int64
	FinishedNs      int64
	Status          string
	TagsSeen        int32
	TagsChanged     int32
	Error           string
	ChainHeadBefore sql.NullString
	ChainHeadAfter  sql.NullString
}

type TaintEvent struct {
	ID            int64
	RemoteID      int64
	RefID         int64
	Reason        string
	ObservationID sql.NullInt64
	FromOid       sql.NullString
	ToOid         sql.NullString
	DetectedAtNs  int64
	AckedAtNs     sql.NullInt64
	AckedBy       sql.NullString
	AckNote       sql.NullString
	Detail        string
}
