// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const getRemoteChainHeadObs = `-- name: GetRemoteChainHeadObs :one
SELECT chain_head_hash, chain_len FROM remotes WHERE id = ?
`

type GetRemoteChainHeadObsRow struct {
	ChainHeadHash []byte
	ChainLen      int64
}

func (q *Queries) GetRemoteChainHeadObs(ctx context.Context, id int64) (GetRemoteChainHeadObsRow, error) {
	row := q.db.QueryRowContext(ctx, getRemoteChainHeadObs, id)
	var i GetRemoteChainHeadObsRow
	err := row.Scan(&i.ChainHeadHash, &i.ChainLen)
	return i, err
}

const insertObservation = `-- name: InsertObservation :execlastid
INSERT INTO observations (
  remote_id, ref_id, sync_id, seq, event_type,
  prev_oid, new_oid, prev_peeled_oid, new_peeled_oid,
  observed_at_ns, prev_hash, row_hash, canonical_meta
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertObservationParams struct {
	RemoteID      int64
	RefID         int64
	SyncID        int64
	Seq           int64
	EventType     string
	PrevOid       sql.NullString
	NewOid        sql.NullString
	PrevPeeledOid sql.NullString
	NewPeeledOid  sql.NullString
	ObservedAtNs  int64
	PrevHash      []byte
	RowHash       []byte
	CanonicalMeta sql.NullString
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertObservation,
		arg.RemoteID,
		arg.RefID,
		arg.SyncID,
		arg.Seq,
		arg.EventType,
		arg.PrevOid,
		arg.NewOid,
		arg.PrevPeeledOid,
		arg.NewPeeledOid,
		arg.ObservedAtNs,
		arg.PrevHash,
		arg.RowHash,
		arg.CanonicalMeta,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const latestObservationForRef = `-- name: LatestObservationForRef :one
SELECT remote_id, seq, row_hash
FROM observations
WHERE ref_id = ?
ORDER BY seq DESC
LIMIT 1
`

type LatestObservationForRefRow struct {
	RemoteID int64
	Seq      int64
	RowHash  []byte
}

func (q *Queries) LatestObservationForRef(ctx context.Context, refID int64) (LatestObservationForRefRow, error) {
	row := q.db.QueryRowContext(ctx, latestObservationForRef, refID)
	var i LatestObservationForRefRow
	err := row.Scan(&i.RemoteID, &i.Seq, &i.RowHash)
	return i, err
}

const replayObservations = `-- name: ReplayObservations :many
SELECT id, remote_id, ref_id, sync_id, seq, event_type,
       prev_oid, new_oid, prev_peeled_oid, new_peeled_oid,
       observed_at_ns, prev_hash, row_hash, canonical_meta
FROM observations
WHERE remote_id = ? AND seq > ?
ORDER BY seq ASC
LIMIT ?
`

type ReplayObservationsParams struct {
	RemoteID int64
	Seq      int64
	Limit    int32
}

func (q *Queries) ReplayObservations(ctx context.Context, arg ReplayObservationsParams) ([]Observation, error) {
	rows, err := q.db.QueryContext(ctx, replayObservations, arg.RemoteID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.RefID,
			&i.SyncID,
			&i.Seq,
			&i.EventType,
			&i.PrevOid,
			&i.NewOid,
			&i.PrevPeeledOid,
			&i.NewPeeledOid,
			&i.ObservedAtNs,
			&i.PrevHash,
			&i.RowHash,
			&i.CanonicalMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
