// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: syncs.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const insertSync = `-- name: InsertSync :execlastid

INSERT INTO syncs (
  remote_id, ` + "`" + `trigger` + "`" + `, started_ns, finished_ns, status,
  tags_seen, tags_changed, error, chain_head_before, chain_head_after
) VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertSyncParams struct {
	RemoteID        int64
	Trigger         string
	StartedNs       int64
	FinishedNs      int64
	Status          string
	TagsSeen        int32
	TagsChanged     int32
	Error           string
	ChainHeadBefore sql.NullString
	ChainHeadAfter  sql.NullString
}

// trigger is a MySQL reserved word → backticked.
func (q *Queries) InsertSync(ctx context.Context, arg InsertSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSync,
		arg.RemoteID,
		arg.Trigger,
		arg.StartedNs,
		arg.FinishedNs,
		arg.Status,
		arg.TagsSeen,
		arg.TagsChanged,
		arg.Error,
		arg.ChainHeadBefore,
		arg.ChainHeadAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listSyncs = `-- name: ListSyncs :many
SELECT id, remote_id, ` + "`" + `trigger` + "`" + `, started_ns, finished_ns, status, tags_seen, tags_changed, error, chain_head_before, chain_head_after FROM syncs
WHERE remote_id = ? AND id > ?
ORDER BY id DESC
LIMIT ?
`

type ListSyncsParams struct {
	RemoteID int64
	ID       int64
	Limit    int32
}

func (q *Queries) ListSyncs(ctx context.Context, arg ListSyncsParams) ([]Sync, error) {
	rows, err := q.db.QueryContext(ctx, listSyncs, arg.RemoteID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sync{}
	for rows.Next() {
		var i Sync
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.Trigger,
			&i.StartedNs,
			&i.FinishedNs,
			&i.Status,
			&i.TagsSeen,
			&i.TagsChanged,
			&i.Error,
			&i.ChainHeadBefore,
			&i.ChainHeadAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
