// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taint.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const ackTaintEvent = `-- name: AckTaintEvent :exec
UPDATE taint_events
SET acked_at_ns = ?, acked_by = ?, ack_note = ?
WHERE id = ? AND acked_at_ns IS NULL
`

type AckTaintEventParams struct {
	AckedAtNs sql.NullInt64
	AckedBy   sql.NullString
	AckNote   sql.NullString
	ID        int64
}

func (q *Queries) AckTaintEvent(ctx context.Context, arg AckTaintEventParams) error {
	_, err := q.db.ExecContext(ctx, ackTaintEvent,
		arg.AckedAtNs,
		arg.AckedBy,
		arg.AckNote,
		arg.ID,
	)
	return err
}

const getTaintEventID = `-- name: GetTaintEventID :one
SELECT id FROM taint_events
WHERE remote_id = ? AND ref_id = ? AND reason = ?
  AND from_oid <=> ? AND to_oid <=> ?
LIMIT 1
`

type GetTaintEventIDParams struct {
	RemoteID int64
	RefID    int64
	Reason   string
	FromOid  sql.NullString
	ToOid    sql.NullString
}

func (q *Queries) GetTaintEventID(ctx context.Context, arg GetTaintEventIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTaintEventID,
		arg.RemoteID,
		arg.RefID,
		arg.Reason,
		arg.FromOid,
		arg.ToOid,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTaintEvent = `-- name: InsertTaintEvent :execlastid
INSERT INTO taint_events (
  remote_id, ref_id, reason,
  observation_id, from_oid, to_oid,
  detected_at_ns, detail
) VALUES (?,?,?,?,?,?,?,?)
ON DUPLICATE KEY UPDATE detected_at_ns = detected_at_ns
`

type InsertTaintEventParams struct {
	RemoteID      int64
	RefID         int64
	Reason        string
	ObservationID sql.NullInt64
	FromOid       sql.NullString
	ToOid         sql.NullString
	DetectedAtNs  int64
	Detail        string
}

// InsertTaintEvent is idempotent on the unique key (remote_id, ref_id, reason,
// from_oid, to_oid). MySQL has no RETURNING; the store reads the id back via
// GetTaintEventID using the same unique key. The ON DUPLICATE KEY UPDATE is a
// self-assignment no-op that preserves the original detected_at_ns.
func (q *Queries) InsertTaintEvent(ctx context.Context, arg InsertTaintEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTaintEvent,
		arg.RemoteID,
		arg.RefID,
		arg.Reason,
		arg.ObservationID,
		arg.FromOid,
		arg.ToOid,
		arg.DetectedAtNs,
		arg.Detail,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listTaintEvents = `-- name: ListTaintEvents :many
SELECT id, remote_id, ref_id, reason,
       observation_id, from_oid, to_oid,
       detected_at_ns, acked_at_ns, acked_by, ack_note, detail
FROM taint_events
WHERE remote_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListTaintEventsParams struct {
	RemoteID int64
	ID       int64
	Limit    int32
}

func (q *Queries) ListTaintEvents(ctx context.Context, arg ListTaintEventsParams) ([]TaintEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTaintEvents, arg.RemoteID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaintEvent{}
	for rows.Next() {
		var i TaintEvent
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.RefID,
			&i.Reason,
			&i.ObservationID,
			&i.FromOid,
			&i.ToOid,
			&i.DetectedAtNs,
			&i.AckedAtNs,
			&i.AckedBy,
			&i.AckNote,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
