-- name: GetRemoteLease :one
SELECT remote_id, holder, acquired_at_ns, expires_at_ns FROM remote_lease WHERE remote_id = ?;

-- UpsertRemoteLease is NOT generated by sqlc; implemented manually in store.go
-- to allow a 5th positional parameter (now_ns) in the ON CONFLICT WHERE clause.
-- This placeholder comment prevents sqlc from erroring on a missing INSERT query.


-- name: DeleteRemoteLease :exec
DELETE FROM remote_lease WHERE remote_id = ? AND holder = ?;
