// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Observation struct {
	ID            int64
	RemoteID      int64
	RefID         int64
	SyncID        int64
	Seq           int64
	EventType     string
	PrevOid       interface{}
	NewOid        interface{}
	PrevPeeledOid interface{}
	NewPeeledOid  interface{}
	ObservedAtNs  int64
	PrevHash      []byte
	RowHash       []byte
	CanonicalMeta interface{}
}

type Ref struct {
	ID               int64
	RemoteID         int64
	TagName          string
	CurrentOid       interface{}
	CurrentPeeledOid interface{}
	IsAnnotated      int64
	FirstOid         interface{}
	FirstSeenNs      int64
	LastSeenNs       int64
	LastChangedNs    int64
	Deleted          int64
	Tainted          int64
	TaintFirstNs     interface{}
	ObservationCount int64
}

type Remote struct {
	ID                  int64
	Url                 string
	NormalizedUrl       string
	Transport           string
	SyncIntervalNs      int64
	StalenessBudgetNs   int64
	TaintAnyTagDeletion int64
	HashAlgo            interface{}
	Status              string
	LastOkNs            int64
	LastErr             string
	ConsecutiveFailures int64
	ChainHeadHash       []byte
	ChainLen            int64
	RemovedAtNs         interface{}
	CreatedAtNs         int64
	UpdatedAtNs         int64
}

type RemoteLease struct {
	RemoteID     int64
	Holder       string
	AcquiredAtNs int64
	ExpiresAtNs  int64
}

type SchemaMigration struct {
	Version     int64
	AppliedAtNs int64
}

type Sync struct {
	ID              int64
	RemoteID        int64
	Trigger         string
	StartedNs       int64
	FinishedNs      int64
	Status          string
	TagsSeen        int64
	TagsChanged     int64
	Error           string
	ChainHeadBefore interface{}
	ChainHeadAfter  interface{}
}

type TaintEvent struct {
	ID            int64
	RemoteID      int64
	RefID         int64
	Reason        string
	ObservationID interface{}
	FromOid       interface{}
	ToOid         interface{}
	DetectedAtNs  int64
	AckedAtNs     interface{}
	AckedBy       interface{}
	AckNote       interface{}
	Detail        string
}
