// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AckTaintEvent(ctx context.Context, arg AckTaintEventParams) error
	AdvanceChainHead(ctx context.Context, arg AdvanceChainHeadParams) error
	AdvanceRemoteChainHead(ctx context.Context, arg AdvanceRemoteChainHeadParams) (int64, error)
	CountRefs(ctx context.Context, remoteID int64) (int64, error)
	CreateRemote(ctx context.Context, arg CreateRemoteParams) (Remote, error)
	// UpsertRemoteLease is NOT generated by sqlc; implemented manually in store.go
	// to allow a 5th positional parameter (now_ns) in the ON CONFLICT WHERE clause.
	// This placeholder comment prevents sqlc from erroring on a missing INSERT query.
	DeleteRemoteLease(ctx context.Context, arg DeleteRemoteLeaseParams) error
	GetChainHead(ctx context.Context, id int64) (GetChainHeadRow, error)
	GetRef(ctx context.Context, arg GetRefParams) (Ref, error)
	GetRemote(ctx context.Context, id int64) (Remote, error)
	GetRemoteByURL(ctx context.Context, normalizedUrl string) (Remote, error)
	GetRemoteChainHead(ctx context.Context, id int64) (GetRemoteChainHeadRow, error)
	GetRemoteChainHeadObs(ctx context.Context, id int64) (GetRemoteChainHeadObsRow, error)
	GetRemoteLease(ctx context.Context, remoteID int64) (RemoteLease, error)
	InsertObservation(ctx context.Context, arg InsertObservationParams) (int64, error)
	InsertSync(ctx context.Context, arg InsertSyncParams) (int64, error)
	InsertTaintEvent(ctx context.Context, arg InsertTaintEventParams) (int64, error)
	LatestObservationForRef(ctx context.Context, refID int64) (LatestObservationForRefRow, error)
	ListRemotes(ctx context.Context, arg ListRemotesParams) ([]Remote, error)
	ListSyncs(ctx context.Context, arg ListSyncsParams) ([]Sync, error)
	ListTags(ctx context.Context, remoteID int64) ([]Ref, error)
	ListTaintEvents(ctx context.Context, arg ListTaintEventsParams) ([]TaintEvent, error)
	ReplayObservations(ctx context.Context, arg ReplayObservationsParams) ([]Observation, error)
	// Returns active, non-removed remotes whose next sync time has passed.
	// last_ok_ns + sync_interval_ns < nowNS
	SelectDueRemotes(ctx context.Context, arg SelectDueRemotesParams) ([]Remote, error)
	SetRefTaint(ctx context.Context, arg SetRefTaintParams) error
	SetRemoteHealth(ctx context.Context, arg SetRemoteHealthParams) error
	SoftDeleteRemote(ctx context.Context, arg SoftDeleteRemoteParams) error
	UpdateRemote(ctx context.Context, arg UpdateRemoteParams) (Remote, error)
	UpsertRef(ctx context.Context, arg UpsertRefParams) (Ref, error)
}

var _ Querier = (*Queries)(nil)
