// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refs.sql

package sqlc

import (
	"context"
)

const countRefs = `-- name: CountRefs :one
SELECT COUNT(*) FROM refs WHERE remote_id = ?
`

func (q *Queries) CountRefs(ctx context.Context, remoteID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRefs, remoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRef = `-- name: GetRef :one
SELECT id, remote_id, tag_name, current_oid, current_peeled_oid, is_annotated, first_oid, first_seen_ns, last_seen_ns, last_changed_ns, deleted, tainted, taint_first_ns, observation_count FROM refs
WHERE remote_id = ? AND tag_name = ?
LIMIT 1
`

type GetRefParams struct {
	RemoteID int64
	TagName  string
}

func (q *Queries) GetRef(ctx context.Context, arg GetRefParams) (Ref, error) {
	row := q.db.QueryRowContext(ctx, getRef, arg.RemoteID, arg.TagName)
	var i Ref
	err := row.Scan(
		&i.ID,
		&i.RemoteID,
		&i.TagName,
		&i.CurrentOid,
		&i.CurrentPeeledOid,
		&i.IsAnnotated,
		&i.FirstOid,
		&i.FirstSeenNs,
		&i.LastSeenNs,
		&i.LastChangedNs,
		&i.Deleted,
		&i.Tainted,
		&i.TaintFirstNs,
		&i.ObservationCount,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, remote_id, tag_name, current_oid, current_peeled_oid, is_annotated, first_oid, first_seen_ns, last_seen_ns, last_changed_ns, deleted, tainted, taint_first_ns, observation_count FROM refs
WHERE remote_id = ?
ORDER BY tag_name ASC
`

func (q *Queries) ListTags(ctx context.Context, remoteID int64) ([]Ref, error) {
	rows, err := q.db.QueryContext(ctx, listTags, remoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ref{}
	for rows.Next() {
		var i Ref
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.TagName,
			&i.CurrentOid,
			&i.CurrentPeeledOid,
			&i.IsAnnotated,
			&i.FirstOid,
			&i.FirstSeenNs,
			&i.LastSeenNs,
			&i.LastChangedNs,
			&i.Deleted,
			&i.Tainted,
			&i.TaintFirstNs,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRefTaint = `-- name: SetRefTaint :exec
UPDATE refs SET tainted = 1, taint_first_ns = ?
WHERE id = ?
`

type SetRefTaintParams struct {
	TaintFirstNs interface{}
	ID           int64
}

func (q *Queries) SetRefTaint(ctx context.Context, arg SetRefTaintParams) error {
	_, err := q.db.ExecContext(ctx, setRefTaint, arg.TaintFirstNs, arg.ID)
	return err
}

const upsertRef = `-- name: UpsertRef :one
INSERT INTO refs (
  remote_id, tag_name,
  current_oid, current_peeled_oid, is_annotated,
  first_oid, first_seen_ns, last_seen_ns, last_changed_ns,
  deleted, tainted, taint_first_ns,
  observation_count
) VALUES (
  ?, ?,
  ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?,
  ?
)
ON CONFLICT (remote_id, tag_name) DO UPDATE SET
  current_oid        = excluded.current_oid,
  current_peeled_oid = excluded.current_peeled_oid,
  is_annotated       = excluded.is_annotated,
  last_seen_ns       = excluded.last_seen_ns,
  last_changed_ns    = excluded.last_changed_ns,
  deleted            = excluded.deleted,
  tainted            = excluded.tainted,
  taint_first_ns     = excluded.taint_first_ns,
  observation_count  = excluded.observation_count
RETURNING id, remote_id, tag_name, current_oid, current_peeled_oid, is_annotated, first_oid, first_seen_ns, last_seen_ns, last_changed_ns, deleted, tainted, taint_first_ns, observation_count
`

type UpsertRefParams struct {
	RemoteID         int64
	TagName          string
	CurrentOid       interface{}
	CurrentPeeledOid interface{}
	IsAnnotated      int64
	FirstOid         interface{}
	FirstSeenNs      int64
	LastSeenNs       int64
	LastChangedNs    int64
	Deleted          int64
	Tainted          int64
	TaintFirstNs     interface{}
	ObservationCount int64
}

func (q *Queries) UpsertRef(ctx context.Context, arg UpsertRefParams) (Ref, error) {
	row := q.db.QueryRowContext(ctx, upsertRef,
		arg.RemoteID,
		arg.TagName,
		arg.CurrentOid,
		arg.CurrentPeeledOid,
		arg.IsAnnotated,
		arg.FirstOid,
		arg.FirstSeenNs,
		arg.LastSeenNs,
		arg.LastChangedNs,
		arg.Deleted,
		arg.Tainted,
		arg.TaintFirstNs,
		arg.ObservationCount,
	)
	var i Ref
	err := row.Scan(
		&i.ID,
		&i.RemoteID,
		&i.TagName,
		&i.CurrentOid,
		&i.CurrentPeeledOid,
		&i.IsAnnotated,
		&i.FirstOid,
		&i.FirstSeenNs,
		&i.LastSeenNs,
		&i.LastChangedNs,
		&i.Deleted,
		&i.Tainted,
		&i.TaintFirstNs,
		&i.ObservationCount,
	)
	return i, err
}
