// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqlc

import (
	"context"
)

type Querier interface {
	AckTaintEvent(ctx context.Context, arg AckTaintEventParams) error
	AdvanceChainHead(ctx context.Context, arg AdvanceChainHeadParams) error
	AdvanceRemoteChainHead(ctx context.Context, arg AdvanceRemoteChainHeadParams) (int64, error)
	// Counts ALL remotes rows including soft-deleted (removed_at_ns set). The seed
	// first-time guard adopts only when this is zero (spec sec.5 / sec.4.5 step 0).
	CountAllRemotes(ctx context.Context) (int64, error)
	CountRefs(ctx context.Context, remoteID int64) (int64, error)
	// MySQL flavor of the remotes query set. No RETURNING (MySQL lacks it):
	// CreateRemote uses :execlastid; the store re-fetches via GetRemote.
	CreateRemote(ctx context.Context, arg CreateRemoteParams) (int64, error)
	// UpsertRemoteLease is NOT generated by sqlc; implemented manually in mysql.go
	// to allow a 5th positional parameter (now_ns) in the freshness predicate.
	// This placeholder comment prevents sqlc from erroring on a missing INSERT query.
	DeleteRemoteLease(ctx context.Context, arg DeleteRemoteLeaseParams) error
	GetChainHead(ctx context.Context, id int64) (GetChainHeadRow, error)
	GetRef(ctx context.Context, arg GetRefParams) (Ref, error)
	GetRefIDByName(ctx context.Context, arg GetRefIDByNameParams) (GetRefIDByNameRow, error)
	GetRemote(ctx context.Context, id int64) (Remote, error)
	GetRemoteByURL(ctx context.Context, normalizedUrl string) (Remote, error)
	GetRemoteChainHead(ctx context.Context, id int64) (GetRemoteChainHeadRow, error)
	GetRemoteChainHeadObs(ctx context.Context, id int64) (GetRemoteChainHeadObsRow, error)
	GetRemoteLease(ctx context.Context, remoteID int64) (RemoteLease, error)
	GetTaintEventID(ctx context.Context, arg GetTaintEventIDParams) (int64, error)
	InsertObservation(ctx context.Context, arg InsertObservationParams) (int64, error)
	// trigger is a MySQL reserved word → backticked.
	InsertSync(ctx context.Context, arg InsertSyncParams) (int64, error)
	// InsertTaintEvent is idempotent on the unique key (remote_id, ref_id, reason,
	// from_oid, to_oid). MySQL has no RETURNING; the store reads the id back via
	// GetTaintEventID using the same unique key. The ON DUPLICATE KEY UPDATE is a
	// self-assignment no-op that preserves the original detected_at_ns.
	InsertTaintEvent(ctx context.Context, arg InsertTaintEventParams) (int64, error)
	LatestObservationForRef(ctx context.Context, refID int64) (LatestObservationForRefRow, error)
	ListRemotes(ctx context.Context, arg ListRemotesParams) ([]Remote, error)
	ListSyncs(ctx context.Context, arg ListSyncsParams) ([]Sync, error)
	ListTags(ctx context.Context, remoteID int64) ([]Ref, error)
	ListTaintEvents(ctx context.Context, arg ListTaintEventsParams) ([]TaintEvent, error)
	PruneSyncs(ctx context.Context, arg PruneSyncsParams) error
	ReplayObservations(ctx context.Context, arg ReplayObservationsParams) ([]Observation, error)
	// Returns active, non-removed remotes whose next sync time has passed.
	// last_ok_ns + sync_interval_ns < nowNS
	SelectDueRemotes(ctx context.Context, arg SelectDueRemotesParams) ([]Remote, error)
	SetRefTaint(ctx context.Context, arg SetRefTaintParams) error
	SetRemoteHealth(ctx context.Context, arg SetRemoteHealthParams) error
	SoftDeleteRemote(ctx context.Context, arg SoftDeleteRemoteParams) error
	UpdateRemote(ctx context.Context, arg UpdateRemoteParams) (int64, error)
	// UpsertRef has no RETURNING in MySQL: INSERT ... ON DUPLICATE KEY UPDATE,
	// then the store reads the id back via GetRefIDByName (unique key remote_id,tag_name).
	UpsertRef(ctx context.Context, arg UpsertRefParams) error
}

var _ Querier = (*Queries)(nil)
