// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refs.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const countRefs = `-- name: CountRefs :one
SELECT COUNT(*) FROM refs WHERE remote_id = ?
`

func (q *Queries) CountRefs(ctx context.Context, remoteID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRefs, remoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRef = `-- name: GetRef :one
SELECT id, remote_id, tag_name, current_oid, current_peeled_oid, is_annotated, first_oid, first_seen_ns, last_seen_ns, last_changed_ns, deleted, tainted, taint_first_ns, observation_count FROM refs
WHERE remote_id = ? AND tag_name = ?
LIMIT 1
`

type GetRefParams struct {
	RemoteID int64
	TagName  string
}

func (q *Queries) GetRef(ctx context.Context, arg GetRefParams) (Ref, error) {
	row := q.db.QueryRowContext(ctx, getRef, arg.RemoteID, arg.TagName)
	var i Ref
	err := row.Scan(
		&i.ID,
		&i.RemoteID,
		&i.TagName,
		&i.CurrentOid,
		&i.CurrentPeeledOid,
		&i.IsAnnotated,
		&i.FirstOid,
		&i.FirstSeenNs,
		&i.LastSeenNs,
		&i.LastChangedNs,
		&i.Deleted,
		&i.Tainted,
		&i.TaintFirstNs,
		&i.ObservationCount,
	)
	return i, err
}

const getRefIDByName = `-- name: GetRefIDByName :one
SELECT id, remote_id FROM refs WHERE remote_id = ? AND tag_name = ? LIMIT 1
`

type GetRefIDByNameParams struct {
	RemoteID int64
	TagName  string
}

type GetRefIDByNameRow struct {
	ID       int64
	RemoteID int64
}

func (q *Queries) GetRefIDByName(ctx context.Context, arg GetRefIDByNameParams) (GetRefIDByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRefIDByName, arg.RemoteID, arg.TagName)
	var i GetRefIDByNameRow
	err := row.Scan(&i.ID, &i.RemoteID)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, remote_id, tag_name, current_oid, current_peeled_oid, is_annotated, first_oid, first_seen_ns, last_seen_ns, last_changed_ns, deleted, tainted, taint_first_ns, observation_count FROM refs
WHERE remote_id = ?
ORDER BY tag_name ASC
`

func (q *Queries) ListTags(ctx context.Context, remoteID int64) ([]Ref, error) {
	rows, err := q.db.QueryContext(ctx, listTags, remoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ref{}
	for rows.Next() {
		var i Ref
		if err := rows.Scan(
			&i.ID,
			&i.RemoteID,
			&i.TagName,
			&i.CurrentOid,
			&i.CurrentPeeledOid,
			&i.IsAnnotated,
			&i.FirstOid,
			&i.FirstSeenNs,
			&i.LastSeenNs,
			&i.LastChangedNs,
			&i.Deleted,
			&i.Tainted,
			&i.TaintFirstNs,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRefTaint = `-- name: SetRefTaint :exec
UPDATE refs SET tainted = 1, taint_first_ns = ?
WHERE id = ?
`

type SetRefTaintParams struct {
	TaintFirstNs sql.NullInt64
	ID           int64
}

func (q *Queries) SetRefTaint(ctx context.Context, arg SetRefTaintParams) error {
	_, err := q.db.ExecContext(ctx, setRefTaint, arg.TaintFirstNs, arg.ID)
	return err
}

const upsertRef = `-- name: UpsertRef :exec
INSERT INTO refs (
  remote_id, tag_name,
  current_oid, current_peeled_oid, is_annotated,
  first_oid, first_seen_ns, last_seen_ns, last_changed_ns,
  deleted, tainted, taint_first_ns,
  observation_count
) VALUES (
  ?, ?,
  ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?,
  ?
)
ON DUPLICATE KEY UPDATE
  current_oid        = VALUES(current_oid),
  current_peeled_oid = VALUES(current_peeled_oid),
  is_annotated       = VALUES(is_annotated),
  last_seen_ns       = VALUES(last_seen_ns),
  last_changed_ns    = VALUES(last_changed_ns),
  deleted            = VALUES(deleted),
  tainted            = VALUES(tainted),
  taint_first_ns     = VALUES(taint_first_ns),
  observation_count  = VALUES(observation_count)
`

type UpsertRefParams struct {
	RemoteID         int64
	TagName          string
	CurrentOid       sql.NullString
	CurrentPeeledOid sql.NullString
	IsAnnotated      int32
	FirstOid         sql.NullString
	FirstSeenNs      int64
	LastSeenNs       int64
	LastChangedNs    int64
	Deleted          int32
	Tainted          int32
	TaintFirstNs     sql.NullInt64
	ObservationCount int64
}

// UpsertRef has no RETURNING in MySQL: INSERT ... ON DUPLICATE KEY UPDATE,
// then the store reads the id back via GetRefIDByName (unique key remote_id,tag_name).
func (q *Queries) UpsertRef(ctx context.Context, arg UpsertRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertRef,
		arg.RemoteID,
		arg.TagName,
		arg.CurrentOid,
		arg.CurrentPeeledOid,
		arg.IsAnnotated,
		arg.FirstOid,
		arg.FirstSeenNs,
		arg.LastSeenNs,
		arg.LastChangedNs,
		arg.Deleted,
		arg.Tainted,
		arg.TaintFirstNs,
		arg.ObservationCount,
	)
	return err
}
