// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remotes.sql

package mysqlc

import (
	"context"
	"database/sql"
)

const advanceChainHead = `-- name: AdvanceChainHead :exec
UPDATE remotes SET chain_head_hash = ?, chain_len = ?
WHERE id = ?
`

type AdvanceChainHeadParams struct {
	ChainHeadHash []byte
	ChainLen      int64
	ID            int64
}

func (q *Queries) AdvanceChainHead(ctx context.Context, arg AdvanceChainHeadParams) error {
	_, err := q.db.ExecContext(ctx, advanceChainHead, arg.ChainHeadHash, arg.ChainLen, arg.ID)
	return err
}

const advanceRemoteChainHead = `-- name: AdvanceRemoteChainHead :execrows
UPDATE remotes
SET chain_head_hash = ?, chain_len = ?
WHERE id = ? AND chain_head_hash = ? AND chain_len = ?
`

type AdvanceRemoteChainHeadParams struct {
	ChainHeadHash   []byte
	ChainLen        int64
	ID              int64
	ChainHeadHash_2 []byte
	ChainLen_2      int64
}

func (q *Queries) AdvanceRemoteChainHead(ctx context.Context, arg AdvanceRemoteChainHeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceRemoteChainHead,
		arg.ChainHeadHash,
		arg.ChainLen,
		arg.ID,
		arg.ChainHeadHash_2,
		arg.ChainLen_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAllRemotes = `-- name: CountAllRemotes :one
SELECT COUNT(*) FROM remotes
`

// Counts ALL remotes rows including soft-deleted (removed_at_ns set). The seed
// first-time guard adopts only when this is zero (spec sec.5 / sec.4.5 step 0).
func (q *Queries) CountAllRemotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllRemotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRemote = `-- name: CreateRemote :execlastid

INSERT INTO remotes (
  url, normalized_url, transport,
  sync_interval_ns, staleness_budget_ns, taint_any_tag_deletion,
  hash_algo, status, last_ok_ns, last_err, consecutive_failures,
  chain_head_hash, chain_len, removed_at_ns, created_at_ns, updated_at_ns
) VALUES (
  ?, ?, ?,
  ?, ?, ?,
  ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?
)
`

type CreateRemoteParams struct {
	Url                 string
	NormalizedUrl       string
	Transport           string
	SyncIntervalNs      int64
	StalenessBudgetNs   int64
	TaintAnyTagDeletion int32
	HashAlgo            sql.NullString
	Status              string
	LastOkNs            int64
	LastErr             string
	ConsecutiveFailures int32
	ChainHeadHash       []byte
	ChainLen            int64
	RemovedAtNs         sql.NullInt64
	CreatedAtNs         int64
	UpdatedAtNs         int64
}

// MySQL flavor of the remotes query set. No RETURNING (MySQL lacks it):
// CreateRemote uses :execlastid; the store re-fetches via GetRemote.
func (q *Queries) CreateRemote(ctx context.Context, arg CreateRemoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRemote,
		arg.Url,
		arg.NormalizedUrl,
		arg.Transport,
		arg.SyncIntervalNs,
		arg.StalenessBudgetNs,
		arg.TaintAnyTagDeletion,
		arg.HashAlgo,
		arg.Status,
		arg.LastOkNs,
		arg.LastErr,
		arg.ConsecutiveFailures,
		arg.ChainHeadHash,
		arg.ChainLen,
		arg.RemovedAtNs,
		arg.CreatedAtNs,
		arg.UpdatedAtNs,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getChainHead = `-- name: GetChainHead :one
SELECT chain_head_hash, chain_len FROM remotes WHERE id = ? LIMIT 1
`

type GetChainHeadRow struct {
	ChainHeadHash []byte
	ChainLen      int64
}

func (q *Queries) GetChainHead(ctx context.Context, id int64) (GetChainHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getChainHead, id)
	var i GetChainHeadRow
	err := row.Scan(&i.ChainHeadHash, &i.ChainLen)
	return i, err
}

const getRemote = `-- name: GetRemote :one
SELECT id, url, normalized_url, transport, sync_interval_ns, staleness_budget_ns, taint_any_tag_deletion, hash_algo, status, last_ok_ns, last_err, consecutive_failures, chain_head_hash, chain_len, removed_at_ns, created_at_ns, updated_at_ns FROM remotes WHERE id = ? LIMIT 1
`

func (q *Queries) GetRemote(ctx context.Context, id int64) (Remote, error) {
	row := q.db.QueryRowContext(ctx, getRemote, id)
	var i Remote
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.Transport,
		&i.SyncIntervalNs,
		&i.StalenessBudgetNs,
		&i.TaintAnyTagDeletion,
		&i.HashAlgo,
		&i.Status,
		&i.LastOkNs,
		&i.LastErr,
		&i.ConsecutiveFailures,
		&i.ChainHeadHash,
		&i.ChainLen,
		&i.RemovedAtNs,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
	)
	return i, err
}

const getRemoteByURL = `-- name: GetRemoteByURL :one
SELECT id, url, normalized_url, transport, sync_interval_ns, staleness_budget_ns, taint_any_tag_deletion, hash_algo, status, last_ok_ns, last_err, consecutive_failures, chain_head_hash, chain_len, removed_at_ns, created_at_ns, updated_at_ns FROM remotes WHERE normalized_url = ? AND removed_at_ns IS NULL LIMIT 1
`

func (q *Queries) GetRemoteByURL(ctx context.Context, normalizedUrl string) (Remote, error) {
	row := q.db.QueryRowContext(ctx, getRemoteByURL, normalizedUrl)
	var i Remote
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.NormalizedUrl,
		&i.Transport,
		&i.SyncIntervalNs,
		&i.StalenessBudgetNs,
		&i.TaintAnyTagDeletion,
		&i.HashAlgo,
		&i.Status,
		&i.LastOkNs,
		&i.LastErr,
		&i.ConsecutiveFailures,
		&i.ChainHeadHash,
		&i.ChainLen,
		&i.RemovedAtNs,
		&i.CreatedAtNs,
		&i.UpdatedAtNs,
	)
	return i, err
}

const getRemoteChainHead = `-- name: GetRemoteChainHead :one
SELECT chain_head_hash, chain_len FROM remotes WHERE id = ?
`

type GetRemoteChainHeadRow struct {
	ChainHeadHash []byte
	ChainLen      int64
}

func (q *Queries) GetRemoteChainHead(ctx context.Context, id int64) (GetRemoteChainHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getRemoteChainHead, id)
	var i GetRemoteChainHeadRow
	err := row.Scan(&i.ChainHeadHash, &i.ChainLen)
	return i, err
}

const listRemotes = `-- name: ListRemotes :many
SELECT id, url, normalized_url, transport, sync_interval_ns, staleness_budget_ns, taint_any_tag_deletion, hash_algo, status, last_ok_ns, last_err, consecutive_failures, chain_head_hash, chain_len, removed_at_ns, created_at_ns, updated_at_ns FROM remotes
WHERE id > ?
ORDER BY id ASC
LIMIT ?
`

type ListRemotesParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ListRemotes(ctx context.Context, arg ListRemotesParams) ([]Remote, error) {
	rows, err := q.db.QueryContext(ctx, listRemotes, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remote{}
	for rows.Next() {
		var i Remote
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.NormalizedUrl,
			&i.Transport,
			&i.SyncIntervalNs,
			&i.StalenessBudgetNs,
			&i.TaintAnyTagDeletion,
			&i.HashAlgo,
			&i.Status,
			&i.LastOkNs,
			&i.LastErr,
			&i.ConsecutiveFailures,
			&i.ChainHeadHash,
			&i.ChainLen,
			&i.RemovedAtNs,
			&i.CreatedAtNs,
			&i.UpdatedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueRemotes = `-- name: SelectDueRemotes :many
SELECT id, url, normalized_url, transport, sync_interval_ns, staleness_budget_ns, taint_any_tag_deletion, hash_algo, status, last_ok_ns, last_err, consecutive_failures, chain_head_hash, chain_len, removed_at_ns, created_at_ns, updated_at_ns FROM remotes
WHERE status = 'active'
  AND removed_at_ns IS NULL
  AND (last_ok_ns + sync_interval_ns) < ?
ORDER BY (last_ok_ns + sync_interval_ns) ASC
LIMIT ?
`

type SelectDueRemotesParams struct {
	LastOkNs int64
	Limit    int32
}

// Returns active, non-removed remotes whose next sync time has passed.
// last_ok_ns + sync_interval_ns < nowNS
func (q *Queries) SelectDueRemotes(ctx context.Context, arg SelectDueRemotesParams) ([]Remote, error) {
	rows, err := q.db.QueryContext(ctx, selectDueRemotes, arg.LastOkNs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Remote{}
	for rows.Next() {
		var i Remote
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.NormalizedUrl,
			&i.Transport,
			&i.SyncIntervalNs,
			&i.StalenessBudgetNs,
			&i.TaintAnyTagDeletion,
			&i.HashAlgo,
			&i.Status,
			&i.LastOkNs,
			&i.LastErr,
			&i.ConsecutiveFailures,
			&i.ChainHeadHash,
			&i.ChainLen,
			&i.RemovedAtNs,
			&i.CreatedAtNs,
			&i.UpdatedAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRemoteHealth = `-- name: SetRemoteHealth :exec
UPDATE remotes SET status = ?, last_err = ?, last_ok_ns = ?, updated_at_ns = ?
WHERE id = ?
`

type SetRemoteHealthParams struct {
	Status      string
	LastErr     string
	LastOkNs    int64
	UpdatedAtNs int64
	ID          int64
}

func (q *Queries) SetRemoteHealth(ctx context.Context, arg SetRemoteHealthParams) error {
	_, err := q.db.ExecContext(ctx, setRemoteHealth,
		arg.Status,
		arg.LastErr,
		arg.LastOkNs,
		arg.UpdatedAtNs,
		arg.ID,
	)
	return err
}

const softDeleteRemote = `-- name: SoftDeleteRemote :exec
UPDATE remotes SET removed_at_ns = ?, updated_at_ns = ? WHERE id = ?
`

type SoftDeleteRemoteParams struct {
	RemovedAtNs sql.NullInt64
	UpdatedAtNs int64
	ID          int64
}

func (q *Queries) SoftDeleteRemote(ctx context.Context, arg SoftDeleteRemoteParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteRemote, arg.RemovedAtNs, arg.UpdatedAtNs, arg.ID)
	return err
}

const updateRemote = `-- name: UpdateRemote :execrows
UPDATE remotes SET
  url                    = ?,
  normalized_url         = ?,
  transport              = ?,
  sync_interval_ns       = ?,
  staleness_budget_ns    = ?,
  taint_any_tag_deletion = ?,
  hash_algo              = ?,
  status                 = ?,
  last_ok_ns             = ?,
  last_err               = ?,
  consecutive_failures   = ?,
  chain_head_hash        = ?,
  chain_len              = ?,
  removed_at_ns          = ?,
  updated_at_ns          = ?
WHERE id = ?
`

type UpdateRemoteParams struct {
	Url                 string
	NormalizedUrl       string
	Transport           string
	SyncIntervalNs      int64
	StalenessBudgetNs   int64
	TaintAnyTagDeletion int32
	HashAlgo            sql.NullString
	Status              string
	LastOkNs            int64
	LastErr             string
	ConsecutiveFailures int32
	ChainHeadHash       []byte
	ChainLen            int64
	RemovedAtNs         sql.NullInt64
	UpdatedAtNs         int64
	ID                  int64
}

func (q *Queries) UpdateRemote(ctx context.Context, arg UpdateRemoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRemote,
		arg.Url,
		arg.NormalizedUrl,
		arg.Transport,
		arg.SyncIntervalNs,
		arg.StalenessBudgetNs,
		arg.TaintAnyTagDeletion,
		arg.HashAlgo,
		arg.Status,
		arg.LastOkNs,
		arg.LastErr,
		arg.ConsecutiveFailures,
		arg.ChainHeadHash,
		arg.ChainLen,
		arg.RemovedAtNs,
		arg.UpdatedAtNs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
